.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge - Debug ]----------"
	@cd "/Users/jerome/Documents/cpp/Section15/Challenge/Challenge" && "$(MAKE)" -f  "Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Challenge - Debug ]----------"
	@cd "/Users/jerome/Documents/cpp/Section15/Challenge/Challenge" && "$(MAKE)" -f  "Challenge.mk" clean
