.PHONY: clean All

All:
	@echo "----------Building project:[ logicalOperators - Debug ]----------"
	@cd "logicalOperators" && "$(MAKE)" -f  "logicalOperators.mk"
clean:
	@echo "----------Cleaning project:[ logicalOperators - Debug ]----------"
	@cd "logicalOperators" && "$(MAKE)" -f  "logicalOperators.mk" clean
