.PHONY: clean All

All:
	@echo "----------Building project:[ ManipBoolean - Debug ]----------"
	@cd "/Users/jerome/Documents/cpp/Section19/ManipBoolean/ManipBoolean" && "$(MAKE)" -f  "ManipBoolean.mk"
clean:
	@echo "----------Cleaning project:[ ManipBoolean - Debug ]----------"
	@cd "/Users/jerome/Documents/cpp/Section19/ManipBoolean/ManipBoolean" && "$(MAKE)" -f  "ManipBoolean.mk" clean
