.PHONY: clean All

All:
	@echo "----------Building project:[ PyramidChallenge - Debug ]----------"
	@cd "PyramidChallenge" && "$(MAKE)" -f  "PyramidChallenge.mk"
clean:
	@echo "----------Cleaning project:[ PyramidChallenge - Debug ]----------"
	@cd "PyramidChallenge" && "$(MAKE)" -f  "PyramidChallenge.mk" clean
