.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge - Debug ]----------"
	@cd "/home/djedje/code/CPP/learn-cpp/Section9/Challenge/Challenge" && "$(MAKE)" -f  "Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Challenge - Debug ]----------"
	@cd "/home/djedje/code/CPP/learn-cpp/Section9/Challenge/Challenge" && "$(MAKE)" -f  "Challenge.mk" clean
