.PHONY: clean All

All:
	@echo "----------Building project:[ RetryChallenge - Debug ]----------"
	@cd "/Users/jerome/Documents/cpp/Section16/RetryChallenge/RetryChallenge" && "$(MAKE)" -f  "RetryChallenge.mk"
clean:
	@echo "----------Cleaning project:[ RetryChallenge - Debug ]----------"
	@cd "/Users/jerome/Documents/cpp/Section16/RetryChallenge/RetryChallenge" && "$(MAKE)" -f  "RetryChallenge.mk" clean
