.PHONY: clean All

All:
	@echo "----------Building project:[ StaticClassMember - Debug ]----------"
	@cd "/Users/jerome/Documents/cpp/Section13/StaticClassMember/StaticClassMember" && "$(MAKE)" -f  "StaticClassMember.mk"
clean:
	@echo "----------Cleaning project:[ StaticClassMember - Debug ]----------"
	@cd "/Users/jerome/Documents/cpp/Section13/StaticClassMember/StaticClassMember" && "$(MAKE)" -f  "StaticClassMember.mk" clean
